[tool.poetry]
name = "cursor_dev"
version = "0.1.0"
description = "X（旧Twitter）のブックマークをリアルタイムで検索し、RAGを実現するPythonツール"
authors = ["AI Developer <dev@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.9.1"
beautifulsoup4 = "^4.12.3"
numpy = "<2.0.0"
matplotlib = "^3.10.0"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
ipykernel = "^6.29.5"
# A2A prototype dependencies
fastapi = "^0.115.12"
uvicorn = "^0.24.0"
httpx = "^0.28.1"
pydantic = "^2.4.0"
python-multipart = "^0.0.6"
starlette = "^0.46.2"
a2a-sdk = "^0.2.4"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
black = "*"
flake8 = "*"
isort = "*"
pytest-asyncio = "^0.25.3"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 79
multi_line_output = 3

[tool.pytest]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --cov=app --cov-report=term-missing"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

