[tool.poetry]
name = "company-crawler"
version = "0.1.0"
description = "企業情報クローラー"
authors = ["AI Assistant <ai@example.com>"]
packages = [
    { include = "app" },
    { include = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.31.0"
beautifulsoup4 = "^4.12.2"
sqlalchemy = "^2.0.23"
pydantic = "^2.5.2"
PyYAML = "^6.0.1"
google-generativeai = "^0.8.3"
openai = "^1.58.1"
respx = "^0.22.0"
httpx = "^0.28.1"
aiohttp = "^3.9.1"
python-dotenv = "^1.0.1"
lxml = "^5.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
flake8 = "^6.1.0"
black = "^23.11.0"
isort = "^5.12.0"
pytest-asyncio = "^0.21.1"
aioresponses = "^0.7.4"
pytest-timeout = "^2.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3

