companies:
  '9984':  # ソフトバンクグループ
    base_url: 'https://group.softbank'
    name: 'ソフトバンクグループ'
    stock_exchange: '東証プライム'
    industry: '情報・通信業'
    paths:
      company_info: '/about/'
      financial_info: '/ir/financials/financial_reports/'
      news: '/ir/news/'
    selectors:
      company:
        name: 'h1.company-name'
        description: 'div.company-profile'
        established_date: 'div.company-info time'
        headquarters: 'div.company-info address'
      financial_info:
        table: 'table.financial-data'
        rows: 'tr'
        columns:
          fiscal_year: 0
          revenue: 1
          operating_income: 2
          net_income: 3
      news:
        list: 'ul.news-list'
        date: 'span.date'
        title: 'span.title'
        link: 'a'
    date_formats:
      news: '%Y年%m月%d日'

  '7203':  # トヨタ自動車
    base_url: 'https://global.toyota'
    name: 'トヨタ自動車'
    stock_exchange: '東証プライム'
    industry: '輸送用機器'
    paths:
      company_info: '/jp/ir/library/annual/'
      financial_info: '/jp/ir/library/results/'
      news: '/jp/ir/news/'
    selectors:
      company:
        name: 'h1.company-name'
        description: 'div.company-profile'
        established_date: 'div.company-info time'
        headquarters: 'div.company-info address'
      financial_info:
        table: 'table.financial-data'
        rows: 'tr'
        columns:
          fiscal_year: 0
          revenue: 1
          operating_income: 2
          net_income: 3
      news:
        list: 'ul.news-list'
        date: 'span.date'
        title: 'span.title'
        link: 'a'
    date_formats:
      news: '%Y年%m月%d日' 