services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile.gpu
      args:
        user_name: $user_name
        group_name: $group_name
    image: $pj_name.app
    container_name: $pj_name.app
    privileged: true
    tty: true
    init: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, compute, video]
    volumes:
      - .:/home/$user_name/workspace
      - ../cognee:/home/$user_name/cognee
      - .ssh/:/home/$user_name/.ssh/
    working_dir: /home/$user_name/workspace
    environment:
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    # sysctls:
    #   - net.core.somaxconn=$somaxconn
    #   - net.ipv4.tcp_syncookies=0
    ports:
      - "13000:3000"    # cognee frontend
      - "17474:7474"    # cognee neo4j
      - "17687:7687"    # cognee neo4j/bolt
      - "15432:5432"    # cognee postgres
      - "18000:8000"    # cognee sse / app
      - "15173:5173"    # web app frontend
      # - "8502:8501"   # streamlit

