FROM nvidia/cuda:11.8.0-devel-ubuntu22.04

LABEL maintainer="tkosht <takehito.oshita.business@gmail.com>"

ENV TZ=Asia/Tokyo
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && apt-get upgrade -y \
    && apt-get install --fix-missing -y sudo build-essential autoconf cmake \
        vim tmux tzdata locales dialog git openssh-server bash-completion htop \
        jq sqlite3 curl nodejs npm default-jre chromium-browser libpq-dev \
        libgeos-dev libsnappy-dev fontconfig fonts-ipaexfont fonts-ipafont \
        libmecab-dev mecab mecab-ipadic-utf8 mecab-utils file \
    && localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN apt-get install -y --fix-missing --no-install-recommends \
        python3.10 \
        python3.10-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel

RUN ln -s /usr/bin/python3.10 /usr/bin/python \
    && ln -s /usr/bin/pdb3 /usr/bin/pdb


COPY bin/install_gh.sh /tmp/install_gh.sh
RUN sh /tmp/install_gh.sh


# DinD
# # c.f https://hub.docker.com/r/billyteves/ubuntu-dind/dockerfile
# # Install Docker and wrapdocker
RUN curl -sSL https://get.docker.com/ | sh
RUN curl -sSL https://raw.githubusercontent.com/billyteves/ubuntu-dind/master/wrapdocker -o /usr/local/bin/wrapdocker
RUN chmod +x /usr/local/bin/wrapdocker
VOLUME /var/lib/docker
ENTRYPOINT ["/usr/local/bin/wrapdocker"]


ENV LANG="ja_JP.UTF-8" \
    LANGUAGE="ja_JP:ja" \
    LC_ALL="ja_JP.UTF-8" \
    TZ="Asia/Tokyo" \
    TERM="xterm"

# ======================== #
# # Install for Tokenizers
WORKDIR /tmp

# # MeCab
# RUN git config --global http.postBuffer 1048576000 \
#     && git clone https://github.com/neologd/mecab-ipadic-neologd.git \
#     && cd mecab-ipadic-neologd && bin/install-mecab-ipadic-neologd -n -a -y

RUN python -m pip install --upgrade pip

# upgrade system
RUN apt-get upgrade -y \
    && apt-get autoremove -y \
    && apt-get clean -y
    # && rm -rf /var/lib/apt/lists/*

# setup general user
ARG user_id=1000
ARG group_id=1000
ARG user_name
ARG group_name

RUN groupadd --gid $group_id $group_name
RUN useradd -s /bin/bash --uid $user_id \
    --gid $group_id -m $user_name
RUN usermod $user_name -G docker,sudo,$group_name
ARG home_dir=/home/$user_name
COPY docker/rc $home_dir

RUN echo $user_name:$user_name | chpasswd
RUN echo $user_name ALL=\(root\) NOPASSWD:ALL \
    > /etc/sudoers.d/$user_name\
    && chmod 0440 /etc/sudoers.d/$user_name

RUN chown -R $user_name:$group_name $home_dir 
USER $user_name

# Poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh


WORKDIR $home_dir

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=dialog

