projects = { "/home/devuser/workspace" = { trust_level = "trusted" } }
model = "gpt-5"
model_provider = "openai"


[mcp_servers.sequential-thinking]
command = "npx"
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]

[mcp_servers.serena]
command = "npx"
args = ["-y", "mcp-remote", "http://localhost:9121/sse", "--transport", "sse-only"]

[mcp_servers.cognee]
command = "sh"
args = ["bin/run_cognee.sh"]


