openapi: 3.0.0
info:
  title: Adaptive Web Crawler API
  description: LLMを使用した適応型WebクローラーのAPI仕様
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: 開発サーバー

paths:
  /crawl:
    post:
      summary: Webページをクロール
      description: 指定されたURLのWebページをクロールし、指定されたデータを抽出します
      operationId: crawlWebPage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CrawlRequest'
      responses:
        '200':
          description: クロール成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrawlResponse'
        '400':
          description: リクエストが不正
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /status/{task_id}:
    get:
      summary: クロールタスクのステータスを取得
      description: 指定されたタスクIDのクロール状況を取得します
      operationId: getTaskStatus
      parameters:
        - name: task_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ステータス取得成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskStatus'
        '404':
          description: タスクが見つからない
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: サーバーエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CrawlRequest:
      type: object
      required:
        - url
        - target_data
      properties:
        url:
          type: string
          description: クロール対象のURL
          example: https://example.com/company
        target_data:
          type: object
          description: 取得対象のデータ定義
          example:
            company_name: 会社名
            established_date: 設立日
            business_description: 事業内容
        options:
          type: object
          description: クロールオプション
          properties:
            max_retries:
              type: integer
              description: 最大リトライ回数
              default: 3
            retry_delay:
              type: number
              description: リトライ間隔（秒）
              default: 1.0
            timeout:
              type: integer
              description: タイムアウト（秒）
              default: 30

    CrawlResponse:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          description: タスクID
          example: task-123456
        status:
          type: string
          description: タスクのステータス
          enum: [pending, running, completed, failed]
        result:
          type: object
          description: クロール結果
          example:
            company_name: ニトリホールディングス
            established_date: 1972年3月
            business_description: 家具・インテリア用品の企画・販売

    TaskStatus:
      type: object
      required:
        - task_id
        - status
      properties:
        task_id:
          type: string
          description: タスクID
        status:
          type: string
          description: タスクのステータス
          enum: [pending, running, completed, failed]
        progress:
          type: object
          description: 進捗情報
          properties:
            current_step:
              type: string
              description: 現在の処理ステップ
            total_steps:
              type: integer
              description: 全処理ステップ数
            percent_complete:
              type: number
              description: 進捗率（%）
        result:
          type: object
          description: クロール結果（完了時のみ）
        error:
          type: object
          description: エラー情報（失敗時のみ）

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: エラーコード
        message:
          type: string
          description: エラーメッセージ
        details:
          type: object
          description: 詳細情報 